### ISSUE TITLE
Errors while trying to test the plugin

### ISSUE THREAD

**Issue by mudrd8mz** [julenpardo/moodle-local_resourceexporter#22]
Attempting to use the plugin leads to the following error messages thrown

    Warning: ZipArchive::addFile(): Invalid or uninitialized Zip object in
    /local/resourceexporter/classes/downloader/downloader.php on line 125

    Warning: ZipArchive::close(): Invalid or uninitialized Zip object in
    /local/resourceexporter/classes/downloader/downloader.php on line 128

Some file named 2_2.zip is then downloaded, but I am unable to extract it:

```
  Archive:  2_2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 2_2.zip or
        2_2.zip.zip, and cannot find 2_2.zip.ZIP, period.
```

**Comment by julenpardo** [comment]
Hi David,

Could you please tell me which PHP version are you using?

**Comment by mudrd8mz** [comment]
PHP 5.6.21

**Comment by julenpardo** [comment]
Okay, I've read that for PHP 5.6 there's a bug with the ZipArchive. It should be fixed just adding a flag when creating the zip.

Currently I'm using PHP 5.5.9. I'll try to upgrade to PHP 5.6 in order to replicate the error and to notice if it gets fixed.

**Comment by mudrd8mz** [comment]
Just wondering, maybe you could try to use the moodle inbuilt wrapper `zip_packer` instead to see if it helps.

**Comment by julenpardo** [comment]
David, I think that just adding ZipArchive::CREATE flag is enough. In my case, the tests have been fixed.

Could you try it also, just in case, before marking this as solved?

**Comment by mudrd8mz** [comment]
Is this fix available in a ZIP published in the plugins directory?

**Comment by julenpardo** [comment]
@mudrd8mz not yet. I thought that it would be better to make the publication of the plugin when it was stable and with the issues closed.

**Comment by julenpardo** [comment]
Hi @mudrd8mz,

First of all, sorry for the delay. The last weeks are letal, when there's still work to do.

I've added the new version in the plugins directory, with the issues you opened fixed (including this), so, I'm setting this as fixed.

Notify me if new errors arise. Thanks.
