### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by mudrd8mz** [julenpardo/moodle-local_resourceexporter#23]
The script created functions in the global scope without valid frankenstyle prefix - see https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

E.g. `init_page()`, `create_zip_and_redirect_to_download()` or `print_error_page()`, `is_admin()` etc.

**Comment by julenpardo** [comment]
Fixed and merged to master, see commit 3af4076 and build nº 191.
