### ISSUE TITLE
Where does the tool check for access rights?

### ISSUE THREAD

**Issue by mudrd8mz** [julenpardo/moodle-local_resourceexporter#24]
I can't see where the exporter performs access right evaluation. That is, where does it check that the resources being exported are those the user has actual access to.

**Comment by julenpardo** [comment]
Hi David,

Several checks are done to avoid unwanted/evil behaviours:

- The login, of course. In line 44 in [create_zip.php](https://github.com/julenpardo/moodle-local_resourceexporter/blob/master/create_zip.php#L44), and in line 32 in [download.php](https://github.com/julenpardo/moodle-local_resourceexporter/blob/master/download.php#L32).
- If the user is enrolled in the course, in line 57 in [create_zip.php](https://github.com/julenpardo/moodle-local_resourceexporter/blob/master/create_zip.php#L57).

At this point, the user would have been accepted, or rejected for the download

Now, for the creation of the zip to download, the permissions of the user for every resource of every type are made:

- In line 60, in [classes/resources/file.php](https://github.com/julenpardo/moodle-local_resourceexporter/blob/master/classes/resources/file.php#L60).
- In line 56, in [classes/resources/url.php](https://github.com/julenpardo/moodle-local_resourceexporter/blob/master/classes/resources/url.php#L56).
- In line 60, in [classes/resources/folder.php](https://github.com/julenpardo/moodle-local_resourceexporter/blob/master/classes/resources/folder.php#L60).

In those lines, [classes/resources/resource::is_module_visible_for_user()](https://github.com/julenpardo/moodle-local_resourceexporter/blob/master/classes/resources/resource.php#L64) is called, receiving the `course id` and `module id`, and then just only using the Module Visibility and Display API.

Please, feel free to ask if the explanation lacks in some aspect or to make any suggestion about the verifications that the tool does.

**Comment by mudrd8mz** [comment]
Sure login and enrolment is not enough. What about capabilities like `mod/resource:view` checked in the context of each module?

**Comment by julenpardo** [comment]
David, isn't that assumed checking the visibility of the moudle using the  [get_fast_modinfo()](https://docs.moodle.org/dev/Module_visibility_and_display#get_fast_modinfo_data) function?

Currently, this is what is done:

```
    protected function is_module_visible_for_user($courseid, $moduleid) {
        $moduleinfo = get_fast_modinfo($courseid);
        $module = $moduleinfo->get_cm($moduleid);
        return $module->uservisible;
    }
```

**Comment by mudrd8mz** [comment]
As far as I understand, modinfo API only affects how / if the module is displayed on the course front page. It is not supposed to be used for checking access to the actual contents of the resource. That is why I would suggest to use external functions like `mod_resource_view_resource` instead.

**Comment by julenpardo** [comment]
Okay, I'll have a look and see how it works, and I'll update this issue's labels accordingly.

**Comment by julenpardo** [comment]
@mudrd8mz , before starting with that, I've manually tried to use the tool in a course where there is a resource that is not visible for the logged user:

![issue-22](https://cloud.githubusercontent.com/assets/12843626/15890771/7f3011ae-2d71-11e6-9918-ae6aac80bb99.PNG)

And the generated zip contains the available "Plantilla.docx", but not the non-accessible "visible url".

Is this what you were speaking about, right?

In any case, this is something that would be convenient to have tested with PHPUnit (I'd swear that it was done, but is not :P ).

**Comment by mudrd8mz** [comment]
I believe that visibility based in hidden/shown status, group membership, conditional access etc. is handled well by the core itself. But it is not what I am talking about. I am talking about capabilities required by these resources' view.php files.

**Comment by julenpardo** [comment]
Okay, now understand your point, sorry.

Well, I've not taken into account that, so it will be a issue to fix.

**Comment by julenpardo** [comment]
@mudrd8mz, first of all, sorry for the delay, I've been quite busy.

Before doing any change, I've checked the current behaviour of the tool, with resources for which the current user's role have prevent/prohibit capability for viewing, and works properly; the resources are not being downloaded. So I guess that the snippet I put above also looks for the capability of the role.

In any case, I will add tests for explicitly test this before closing this.
